namespace PRISM.DTO.MainShift
{
    public class LNEDetailModel
    {
        public long Id { get; set; }
        public string? Ptonumber { get; set; }
        public string? OrderRevision { get; set; }
        public string? JobNumber { get; set; }
        public string? WeekNo { get; set; }
        public DateTime? StartDate { get; set; }
        public string? Shift { get; set; }
        public string? TrainOrderType { get; set; }
        public string? MachineType { get; set; }
        public string? WorksiteDetails { get; set; }
        public string? StartTime { get; set; }
        public DateTime? FinishDate { get; set; }
        public string? FinishTime { get; set; }
        public string? Mileage { get; set; }
        public string? YardOut { get; set; }
        public string? YardIn { get; set; }
        public string? LineToArriveOn { get; set; }
        public string? WorkDescription { get; set; }
        public string? WorksiteDescriptor { get; set; }
        public string? ConsistSleeperType { get; set; }
        public string? Supplier { get; set; }
        public string? MachineNum { get; set; }
        public string? Contractor { get; set; }
        public string? PpreDriver { get; set; }
        public string? PpreOperator { get; set; }
        public string? PpreAssessor { get; set; }
        public string? Customer { get; set; }
        public string? Route { get; set; }
        public string? OrderStatus { get; set; }
        public string? WorksiteNo { get; set; }
        public string? Ppsreference { get; set; }
        public string? Remarks { get; set; }
        public string? OrderDate { get; set; }
        public string? EnteredBy { get; set; }
        public string? CancellationDate { get; set; }
        public string? CancelledBy { get; set; }
        public string? PossessionDetails { get; set; }
        public string? WorksiteElr { get; set; }
        public string? WorkYardage { get; set; }
        public string? PartOfBlockade { get; set; }
        public string? PriorityStatusShift { get; set; }
        public string? MachineSupply { get; set; }
        public string? CnupledMachines { get; set; }
        public string? TrainId { get; set; }
        public string? TimeOutOfYard { get; set; }
        public string? TimeBackToYard { get; set; }
        public string? WonNumber { get; set; }
        public string? PpreLogNumber { get; set; }
        public string? PpreCompany { get; set; }
        public string? PpreFailureComments { get; set; }
        public string? PpreSummary { get; set; }
        public string? PpreEmptyComment { get; set; }
        public string? PprePlannedWork { get; set; }
        public string? PpreInternalComments { get; set; }
        public DateTime? PpreShiftDate { get; set; }
        public string? PpreDay { get; set; }
        public string? PprePlannedHours { get; set; }
        public string? PprePathTime { get; set; }
        public string? PpreHeadCode { get; set; }
        public string? ShiftNo { get; set; }
        public string? HeadCode { get; set; }
        public int RowIndex { get; set; }
        public int TotalRecords { get; set; }
        public int TotalPages { get; set; }
        public int Start { get; set; }
        public int End { get; set; }
        public string? MachineMgr { get; set; }
        public string? StartDateTime { get; set; }
        public string? FinishDateTime { get; set; }
        public string? PPreContractor { get; set; }
        public string? PpreTQSPhone { get; set; }
        public string? PprePICOPPhone { get; set; }
        public string? OutShortCode { get; set; }
        public string? InShortCode { get; set; }
		public string? OutName { get; set; }
		public string? InName { get; set; }
		public string? OutStanox { get; set; }
		public string? InStanox { get; set; }
		public string? PpreAct { get; set; }
		public string? PpreDra { get; set; }
		public string? PpreRTNo { get; set; }
		public string? PpreES { get; set; }
		public string? PpreTQS { get; set; }
		public string? PpreMCO { get; set; }
		public string? PpreAPM { get; set; }
		public string? PpreAPMPhone { get; set; }
        public string? PpreOTML { get; set; }
        public string? ShiftTimeDetail { get; set; }
        public string? PprePlfield { get; set;}
        public string? WorkCompleted { get; set; }
    }
}
